### ISSUE TITLE
Make sure the app is very resilient to errors

### ISSUE THREAD

**Issue by Martoon-00** [serokell/tzbot#18]
# Clarification and motivation

After implementing the main logic, let's take extra measures to make sure that the application does not crash due to networking or internal errors.

# Acceptance criteria

* Some appropriate threading / errors handling model is introduced to make the app never crash.
* It should still be possible to send `SINGINT` and stop the app.

**Comment by YuriRomanowski** [comment]
What are we supposed to check? If the network goes down, I think that the bot will just do nothing, because it won't be able to receive any events. Internal errors can occur only because of our programming errors, we can either find them ourselves by testing or find them in the logs when the app is working. `SIGINT` is already handled by the default Haskell handler. Am I missing something?

**Comment by Martoon-00** [comment]
It's rather a talk about exceptions handling, what I mean is to go over every block of code and ask yourself: if out of the sudden an exception is raised here, will it be eventually handled normally? Wouldn't it cause bot to stop working?

It might be that network stops working at such a moment that we received a message but then fail to invoke our network action. Or some `StackOverflow` exception may fly in at any moment of time.

---

E.g. one common thing to do: find every use of `forever` and wrap the looped action into `catchAny` call, so that any sudden exception from inside does not abort the working thread - even if I cannot imagine a situation when such exception can happen; it's an extra safety measure.
