### ISSUE TITLE
Cache slack data

### ISSUE THREAD

**Issue by dcastro** [serokell/tzbot#7]
# Clarification and motivation

We have [2 methods](https://github.com/serokell/tzbot/blob/main/src/TzBot/Slack/WebAPI/Class.hs) for retrieving data from Slack's Web API, `getUser` and `getChannelMembers`. Both endpoints are subject to Slack's [rate limits](https://api.slack.com/docs/rate-limits), so we should refrain from making needless calls to avoid hitting these limits.

To this end, we should cache the data retrieved from these 2 methods.

To keep a clean separation of concerns, we should implement the caching as a monad transformer that has an instance of `WebApi` and can be stacked on top of `WebAPIM`.

Bonus points: we should also make sure that cache entries don't all expire at the same time (otherwise, we risk having to refresh hundreds of entries at once and, thus, hitting the rate limits). Expiry times should be somewhat randomized. Users' info should be cached for about 1h ~ 1h30m and channels' membership info for about 1~2 minutes.

# Acceptance criteria

* The data retrieved from `getUser` and `getChannelMembers` is cached
* Bonus: each cache entry's expiry time is random (within some bounds)

**Comment by YuriRomanowski** [comment]
There are two options that we can pick to implement caching:
* use Haskell data structures and store them as the bot's state
* use some external service, e.g. [Redis](https://redis.io/)

What we need to keep in the cache:
* Channel members
* Users with their timezones
* Maybe, we will need to store some data about all messages to handle messages editing, but it strongly depends on how exactly we handle it (we can discuss it here [#4](https://github.com/serokell/tzbot/issues/4))

It seems that the only (doubtful) advantage of the Haskell data structures is that we don't have to think about any extra services except our bot. But using Redis inside `docker` is easy too container is rather easy too, @alexd1971 mentioned that it is very lightweight. What we obtain in this case:
* Free expiration handling. In Redis, it is just built in, while for Haskell we need to intend it ourselves (maybe running extra thread in the background that will clean up our cache periodically)
* Easier implementation from the Haskell point of view, again, because we don't have to work with any `IORef`s and so on
* Data is not erased on the bot reloading
Something else?

So, for me it seems that using Redis here is much more rational and natural. Do you agree?

**Comment by Martoon-00** [comment]
Thanks for writing this down :+1: 

---

Let me serve as an advocate for the Haskell-only approach (personally I don't have strong preference here).

### On the advantages of Redis

> Free expiration handling

I believe there are libraries that provide caches with expiration.

> Easier implementation from the Haskell point of view

That's not obvious :thinking:   Maybe for `IORef` we will have to provide a couple of helpers, but for the Redis approach we will also need extra code - at least to handle serialization.

> Data is not erased on the bot reloading

I believe that channel members and user info form not that large amount of info and we should not struggle with loading them upon server start.

On storing old messages, if we eventually need them - we really don't want to lose them, that's true. But this seems to me to be rather a use case for database, not for Redis (I may be wrong though, I don't have large experience on this topic).

### On disadvantages of Redis

* If we go with it, we will introduce a responsiveness penalty (communication between services + serialization), although this seems minor on the background of communication with Slack API.
* Overall complexity increase of setup.

Well, I suppose it all mostly boils down to the common debate - whether is it worth using microservices with all their pros & cons or not.

Again, these are just my thoughts, I personally don't see anything that would make one approach outstand the other, would be interested to see any of them implemented.

**Comment by YuriRomanowski** [comment]
Well, OK, I think that if we are not very concerned about the data persistence then Haskell data structures will rather suite our needs too. Let's try with it then, later we can switch to something else.

**Comment by alexd1971** [comment]
Here is a Haskell caching library: https://hackage.haskell.org/package/cache

**Comment by alexd1971** [comment]
Why do we need random expiry time?

**Comment by YuriRomanowski** [comment]
> Why do we need random expiry time? Maybe it would be better to use configuration parameter for this?

@dcastro gave the motivation of this:
>  we should also make sure that cache entries don't all expire at the same time

So, it's assumed that we use the configuration parameter for the mean expiry time, with some interval of some amplitude included.
For example, 20min +- 5min.
